#!/bin/bash

# Function to display information about a subdomain
display_info() {
    local subdomain=$1
    local domain=$2
    local record_type=$3
    local destination=$4

    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Check if the correct number of arguments is provided
if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi

# Set the domain and subdomain variables
domain=$1
subdomain=$2

# Set the default subdomains
subdomains=("www" "lb-01" "web-01" "web-02")

# Loop through subdomains and display information
for sub in "${subdomains[@]}"; do
    if [ -z "$subdomain" ] || [ "$sub" == "$subdomain" ]; then
        result=$(dig "$sub.$domain" | awk '/ANSWER SECTION:/ {getline; print $4}')
        if [ -n "$result" ]; then
            record_type=$(dig "$sub.$domain" | awk '/ANSWER SECTION:/ {getline; print $3}')
            display_info "$sub" "$domain" "$record_type" "$result"
        fi
    fi
done
