#!/usr/bin/env bash
# Display "To infinity and beyond indefinitely"  ---> 
# set a trap SIGTERM ----> Display "Iam Invicible"

trap "echo I am invincible!!!" SIGTERM
while true ;
do
	echo "To infinity and beyond"
	sleep 2
done;
